name: 🐞 Bug Report
description: help us to improve ourself
body:
 - type: textarea
   attributes:
    label: Bug reproduction steps or occurrence process
    description: Enter details about your bug.
    placeholder: |
     1. Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version
     2. Contents of value.yaml 
     3. Your helm command 
     4. See error...
   validations:
    required: true
 - type: textarea
   attributes:
    label: Are you using any custom parameters or values?
    description: Add any parameter used via `--set` or as a `values.yaml` customization.
 - type: textarea
   attributes:
    label: What is the expected result?
